### ISSUE TITLE
DDOS-Guard timeouts

### ISSUE THREAD

**Issue by judyynailss** [ThePhaseless/Byparr#15]
**Describe the bug**
Hey there, 

I've been looking for a good replacement for FlareSolverr since it's been struggling to connect to DDoS-Guard websites, in this case simpcity.su. When using Byparr, I seem to hit a wall where it finds a challenge, then gets stuck doing... Well, I'm not sure, but it just sits there.

I know that this project is primarily focused on Cloudflare challenges, but I thought I would mention this in the chance that you can find a way to fix it.

**I've:**
- [X] - read Loop Warning on Readme.
- [X] - done the troubleshooting from Readme. <-- Yes, I actually did this.
- [X] - checked if such issue already exists. 

**Docker host (please complete the following information):**
 - OS: Built in both Windows 11 22h3 and Ubuntu 24.04.1 (WSL)
 - Platform and model: PC, Laptop
 - Architecture x86/64

**Additional context**
I've tried building the docker container in both Ubuntu and Windows 11 just to make sure it wasn't an issue with either, connected to the VNC to verify that Chrome works (it does), and read through all of other issues, but I haven't noticed anything similar to this. I'm not having any issues running Byparr itself, just DDoS-Guard issues.

**Comment by ThePhaseless** [comment]
will look into it this week, thx for issue

**Comment by judyynailss** [comment]
That was the impression I was under as well, but it appears it might be getting caught up with a weird mix of DDoS Guard and hCaptcha, I'm not sure exactly what's going on, but I'm trying to see if I can narrow it down to a more specific error.

**Comment by ThePhaseless** [comment]
If you can, please, I can't replicate. My requests are not even triggering the protection

**Comment by ThePhaseless** [comment]
Hi, could you pull the latest release and try again?

**Comment by ThePhaseless** [comment]
I'm closing since a lot of things changed, can't replicate and no response from the OP
