### ISSUE TITLE
Suggesion - AI?

### ISSUE THREAD

**Issue by kmadaras** [ThePhaseless/Byparr#18]
It seems to me this is ripe for AI, any chance that an AI version is on the horizon, it'd be a big change, yet could really differentiate the project, particularly with the latest vision models.  Just throwing it out there.

**Comment by ThePhaseless** [comment]
Hi, AI is too unpredictable, but currently I'm experimenting with something simpler: SeleniumBase, which now has supports nodriver, has something that looks like searching the screen for captcha box. I will push the branch if I get any satisfying results
