### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by plokijuter** [ThePhaseless/Byparr#4]
Was working great for weeks but stopped working about 5 days ago.

byparr-byparr-1  | INFO:     Uvicorn running on http://0.0.0.0:8191 (Press CTRL+C to quit)
byparr-byparr-1  | INFO:     Request: cmd='request.get' url='https://www.ygg.re/engine/search?category=2145&do=search&order=desc&sort=publish_date' maxTimeout=60000
byparr-byparr-1  | INFO:     Found challenge
byparr-byparr-1  | INFO:     172.18.0.1:51208 - "POST /v1 HTTP/1.1" 500 Internal Server Error
byparr-byparr-1  | ERROR:    Exception in ASGI application
byparr-byparr-1  | Traceback (most recent call last):
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
byparr-byparr-1  |     result = await app(  # type: ignore[func-returns-value]
byparr-byparr-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
byparr-byparr-1  |     return await self.app(scope, receive, send)
byparr-byparr-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
byparr-byparr-1  |     await super().__call__(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
byparr-byparr-1  |     await self.middleware_stack(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
byparr-byparr-1  |     raise exc
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
byparr-byparr-1  |     await self.app(scope, receive, _send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
byparr-byparr-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
byparr-byparr-1  |     raise exc
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
byparr-byparr-1  |     await app(scope, receive, sender)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
byparr-byparr-1  |     await self.middleware_stack(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
byparr-byparr-1  |     await route.handle(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
byparr-byparr-1  |     await self.app(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
byparr-byparr-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
byparr-byparr-1  |     raise exc
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
byparr-byparr-1  |     await app(scope, receive, sender)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
byparr-byparr-1  |     response = await func(request)
byparr-byparr-1  |                ^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
byparr-byparr-1  |     raw_response = await run_endpoint_function(
byparr-byparr-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
byparr-byparr-1  |     return await dependant.call(**values)
byparr-byparr-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/app/main.py", line 40, in read_item
byparr-byparr-1  |     challenged = await asyncio.wait_for(bypass_cloudflare(page), timeout=timeout)
byparr-byparr-1  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
byparr-byparr-1  |     return await fut
byparr-byparr-1  |            ^^^^^^^^^
byparr-byparr-1  |   File "/app/src/utils/browser.py", line 78, in bypass_cloudflare
byparr-byparr-1  |     if elem is None:
byparr-byparr-1  |        ^^^^
byparr-byparr-1  | UnboundLocalError: cannot access local variable 'elem' where it is not associated with a value
byparr-byparr-1  | INFO:     Request: cmd='request.get' url='https://www.ygg.re/engine/search?category=2145&do=search&order=desc&sort=publish_date' maxTimeout=60000
byparr-byparr-1  | INFO:     Found challenge
byparr-byparr-1  | INFO:     172.18.0.1:44642 - "POST /v1 HTTP/1.1" 500 Internal Server Error
byparr-byparr-1  | ERROR:    Exception in ASGI application
byparr-byparr-1  | Traceback (most recent call last):
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
byparr-byparr-1  |     result = await app(  # type: ignore[func-returns-value]
byparr-byparr-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
byparr-byparr-1  |     return await self.app(scope, receive, send)
byparr-byparr-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
byparr-byparr-1  |     await super().__call__(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
byparr-byparr-1  |     await self.middleware_stack(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
byparr-byparr-1  |     raise exc
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
byparr-byparr-1  |     await self.app(scope, receive, _send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
byparr-byparr-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
byparr-byparr-1  |     raise exc
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
byparr-byparr-1  |     await app(scope, receive, sender)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
byparr-byparr-1  |     await self.middleware_stack(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
byparr-byparr-1  |     await route.handle(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
byparr-byparr-1  |     await self.app(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
byparr-byparr-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
byparr-byparr-1  |     raise exc
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
byparr-byparr-1  |     await app(scope, receive, sender)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
byparr-byparr-1  |     response = await func(request)
byparr-byparr-1  |                ^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
byparr-byparr-1  |     raw_response = await run_endpoint_function(
byparr-byparr-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
byparr-byparr-1  |     return await dependant.call(**values)
byparr-byparr-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/app/main.py", line 40, in read_item
byparr-byparr-1  |     challenged = await asyncio.wait_for(bypass_cloudflare(page), timeout=timeout)
byparr-byparr-1  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
byparr-byparr-1  |     return await fut
byparr-byparr-1  |            ^^^^^^^^^
byparr-byparr-1  |   File "/app/src/utils/browser.py", line 78, in bypass_cloudflare
byparr-byparr-1  |     if elem is None:
byparr-byparr-1  |        ^^^^
byparr-byparr-1  | UnboundLocalError: cannot access local variable 'elem' where it is not associated with a value
byparr-byparr-1  | INFO:     Request: cmd='request.get' url='https://www.ygg.re/engine/search?category=2145&do=search&order=desc&sort=publish_date' maxTimeout=60000
byparr-byparr-1  | INFO:     Found challenge
byparr-byparr-1  | INFO:     172.18.0.1:49262 - "POST /v1 HTTP/1.1" 500 Internal Server Error
byparr-byparr-1  | ERROR:    Exception in ASGI application
byparr-byparr-1  | Traceback (most recent call last):
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
byparr-byparr-1  |     result = await app(  # type: ignore[func-returns-value]
byparr-byparr-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
byparr-byparr-1  |     return await self.app(scope, receive, send)
byparr-byparr-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
byparr-byparr-1  |     await super().__call__(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
byparr-byparr-1  |     await self.middleware_stack(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
byparr-byparr-1  |     raise exc
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
byparr-byparr-1  |     await self.app(scope, receive, _send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
byparr-byparr-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
byparr-byparr-1  |     raise exc
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
byparr-byparr-1  |     await app(scope, receive, sender)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
byparr-byparr-1  |     await self.middleware_stack(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
byparr-byparr-1  |     await route.handle(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
byparr-byparr-1  |     await self.app(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
byparr-byparr-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
byparr-byparr-1  |     raise exc
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
byparr-byparr-1  |     await app(scope, receive, sender)
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
byparr-byparr-1  |     response = await func(request)
byparr-byparr-1  |                ^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
byparr-byparr-1  |     raw_response = await run_endpoint_function(
byparr-byparr-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
byparr-byparr-1  |     return await dependant.call(**values)
byparr-byparr-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/app/main.py", line 40, in read_item
byparr-byparr-1  |     challenged = await asyncio.wait_for(bypass_cloudflare(page), timeout=timeout)
byparr-byparr-1  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
byparr-byparr-1  |   File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
byparr-byparr-1  |     return await fut
byparr-byparr-1  |            ^^^^^^^^^
byparr-byparr-1  |   File "/app/src/utils/browser.py", line 78, in bypass_cloudflare
byparr-byparr-1  |     if elem is None:
byparr-byparr-1  |        ^^^^
byparr-byparr-1  | UnboundLocalError: cannot access local variable 'elem' where it is not associated with a value

**Comment by ThePhaseless** [comment]
Hi, please repull and check again!

**Comment by plokijuter** [comment]
Thanks! Will do!

**Comment by ThePhaseless** [comment]
Hi, I've just pushed more fixes, please try again if previous code failed
