### ISSUE TITLE
ARM64 Builds

### ISSUE THREAD

**Issue by cacafuti8888** [ThePhaseless/Byparr#5]
It would be amazing if you can pull an image for arm64 architecture....

**Comment by ThePhaseless** [comment]
Hi, that's a great idea, I will try to do it this week

**Comment by ThePhaseless** [comment]
I've added an build to actions, should now build for arm64 as well!

**Comment by ThePhaseless** [comment]
Hi, #3 looks like the same issue, i will close this as duplicate
